FROM oven/bun:1-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./
COPY ./turbo.json ./turbo.json

RUN bun install

COPY ./apps/init-service ./apps/init-service

COPY . .

EXPOSE 3001

CMD [ "bun","run","src/index.ts" ]