FROM oven/bun:1-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./
COPY ./package.json ./
COPY ./turbo.json ./

RUN bun install

COPY ./apps/orchestrator ./apps/orchestrator

COPY . .

EXPOSE 3002

CMD [ "bun","run","src/index.ts" ]